curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip & curl --request POST \
  --url http://localhost:8080 \
  --header 'content-type: multipart/form-data' \
  --form a=@/Users/sanyamkhurana/Downloads/Poedit-2.2.1.zip
